---
  
- name: Wildcard Certs
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - set_fact:
        work_dir_name: wildcard_certs 
        resources_dir: "{{ resources_base_dir }}/wildcard_certs"
    - include_role:
        name: ../roles/wildcard_cert
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/wildcard_certs
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
