---

# reference
#     https://github.com/redhat-cop/openshift-lab-origin/blob/master/OpenShift4/Lets_Encrypt_Certificates_for_OCP4.adoc#installing-certificates-for-the-api
#     https://www.openshift.com/blog/requesting-and-installing-lets-encrypt-certificates-for-openshift-4


- name: Create secret in {{ ingress_namespace }}
  shell: |
    oc create secret tls router-certs --cert={{ WILDCARD_CERTDIR }}/fullchain.cer --key={{ WILDCARD_CERTDIR }}/{{ WILDCARD_KEY_NAME }} -n {{ ingress_namespace }}

- name: Patch IngressController in {{ ingress_controller_namespace }}
  shell: |
    oc patch ingresscontroller default -n {{ ingress_controller_namespace }} --type=merge --patch='{"spec": { "defaultCertificate": { "name": "router-certs" }}}'

# TO-DO:  Check status of router pods in openshift-ingress namespace
